# from . import ImageMixin
from . import webhook_event
from . import res_company
from . import city
from . import branch
from . import product_brand
from . import account_tax
from . import product_category
from . import product_options
from . import product_template
from . import res_partner
from . import sale_order
from . import payment
from . import salla_dashboard
from . import product_tags
from . import sale_order_tags
from . import shipping_company
from . import shipping_rules
from . import customer_groups
from . import shipping_zones
from . import sale_status
from . import affiliates
from . import advertisement
from . import coupons
from . import offers
from . import res_currency